name: Deploy to PyPi

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Build the package
      run: |
        python -m pip install --upgrade pip
        python -m pip install twine
        python -m pip install .
        python setup.py sdist

    - name: Twine Check
      run: |
        python -m twine check dist/*

  test:
    runs-on: ubuntu-latest

    needs: build

    steps:

      - uses: actions/checkout@v3

      - name: Run PyTests
        run: |
          pip install -r requirements.txt
          pytest


  upload:
    runs-on: ubuntu-latest

    needs: test

    steps:

      - uses: actions/checkout@v3

      - name: Upload to PyPi
        uses: pypa/gh-action-pypi-publish@master
        with:
            user=__token__
            password=${{ secrets.PYPI_SECRET }}
            repository_url=https://pypi.org/legacy/rustkit
